# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/etri/data_train.npy
  label_path: ./data/etri/actions_train.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/etri/data_test.npy
  label_path: ./data/etri/actions_test.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 55
  num_point: 25
  num_person: 1
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 50]

# training
num_epoch: 60
device: [0, 1, 2]
batch_size: 48
forward_batch_size: 48
test_batch_size: 96
nesterov: True
