debug: False
# feeder
feeder: feeders.feeder_anonymization.Feeder
train_feeder_args:
  data_path: ./data/etri/data_train.npy
  gender_label_path: ./data/etri/genders_train.pkl
  action_label_path: ./data/etri/actions_train.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder: feeders.feeder_anonymization_test.Feeder

test_feeder_args:
  debug: False
  data_path: ./data/etri/data_test.npy
  gender_label_path: ./data/etri/genders_test.pkl
  action_label_path: ./data/etri/actions_test.pkl

# model
anonymizer_model: model.anonymization_res.Anonymizer
model_args:
  num_point: 25
  num_person: 1
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

action_model: model.msg3d.Model
action_model_args:
  num_class: 55
  num_point: 25
  num_person: 1
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

privacy_model: model.gender_classifier.Model
privacy_model_args:
  num_class: 2
  num_point: 25
  num_person: 1
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.00001 # L2 norm
anonymizer_base_lr: 0.0018
privacy_base_lr: 0.0030
step: [10, 20]

# training
num_epoch: 40
device: [0, 1, 2]
batch_size: 30
nesterov: True

anonymizer_steps: [0]
privacy_steps: [1]

test_action:
  batch_size: 60

test_privacy:
  batch_size: 60

pretrained_action: work_dir/action_classifier/action_1/weights/weights-57-81681.pt
pretrained_privacy: work_dir/gender_classifier/gender_1/weights/weights-13-22347.pt
pretrained_privacy_test: [
    work_dir/gender_classifier/gender_4/weights/weights-18-10314.pt,
  ]

alpha: 0.1  # privacy loss
beta: 0.0067 # action loss
