debug: False
# feeder
feeder: feeders.feeder_anonymization.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  gender_label_path: ./data/ntu/xview/train_label_reid.pkl
  action_label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder: feeders.feeder_anonymization_test.Feeder

test_feeder_args:
  debug: False
  data_path: ./data/ntu/xview/val_data_joint.npy
  gender_label_path: ./data/ntu/xview/val_label_reid.pkl
  action_label_path: ./data/ntu/xview/val_label.pkl

# model
anonymizer_model: model.anonymization_res.Anonymizer
model_args:
  num_point: 25
  num_person: 2
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

action_model: model.msg3d.Model
action_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

privacy_model: model.msg3d.Model
privacy_model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.00001 # L2 norm
anonymizer_base_lr: 0.0018
privacy_base_lr: 0.003
step: [10, 20]

# training
num_epoch: 50
device: [0, 1]
batch_size: 24
nesterov: True

anonymizer_steps: [0]
privacy_steps: [1]

test_action:
  batch_size: 60

test_privacy:
  batch_size: 60

pretrained_action: work_dir/ntu_action/weights/weights-47-55272.pt
pretrained_privacy: work_dir/reid_train/1028_2/weights/weights-44-22968.pt
pretrained_privacy_test: [
    work_dir/reid_train/1028_2/weights/weights-44-22968.pt,
    work_dir/reid_train/1101_1/weights/weights-34-21318.pt
  ]

alpha: 0.1  # privacy loss
beta: 0.0067 # action loss
